version: "3.8"

services:
  db:
    image: postgres:13
    container_name: cvet-ochey-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cvetochey
    ports:
      - "5432:5432"

  backend:
    image: nesterrovv/cvet-ochey:1.0
    container_name: cvet-ochey-backend
    depends_on:
      - db
    environment:
      - DATABASE_DRIVER=jdbc:postgresql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_LOGIN=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=cvetochey

    # Пробрасываем порт 8080 наружу
    ports:
      - "8080:8080"