version: '3.8'

services:
  frontend:
    image: vezon/cvetochey
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://84.201.131.26:8080
    restart: unless-stopped
