server:
  port: 8080

spring:
  application:
    name: cvet-ochey
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
  datasource:
    url: ${DATABASE_DRIVER}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_LOGIN}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: backend
  endpoint:
    prometheus:
      enabled: true